### PR TITLE
Add a function to return all the keys of the entries that hold the same value.

### PR DESCRIPTION
**Pull request by ahmed-debbech**
Hi!
I just added a new function to the API which searches for a given value in the whole map and returns all the keys that holds that value. 
`// get all enteries that have the same values returned as an array of keys
// it actually iterates the whole map as hashmap_iterate does.
void ** hashmap_get_same_values(hashmap * m, uintptr_t value);`

### CODE REVIEW

**Review by Mashpoe — COMMENTED** [review]
I can see how this could be useful, but I don't think this is the best way to go about implementing it. How will the user know the number of resulting keys? If you already know the number of matches ahead of time, couldn't you just let the user create their own array and pass in the address and length? Since keys are not necessarily null-terminated, how will the user know the length of each key?

I think the best way to go about this would be to follow the conventions of the rest of the library by using a callback solution. That way, not only will the user know the length of each key that they get, but they can make a count of each key if they see fit. I also like a callback solution better because if the user just wants to perform an operation on each key (e.g. printing them) then they won't have to allocate memory and then deal with the responsibility of freeing it.

I'll consider merging a callback solution, but I'm still not too sure if it's worth adding this feature at all, because any practical solution would be almost identical to just calling `hashmap_iterate()`. The only advantage there would be in adding a new function is that it could save the user from having to write a two-line if statement:

```c
// callback function
void get_keys(void* key, size_t ksize, uintptr_t value, void* usr)
{
    // the aforementioned two-line if statement.
    // not too big of a deal imo
    if ((void*)value != usr)
        return;
    
    // do something with the key now
}

/*
...
*/

hashmap_iterate(m, get_keys, value_to_match);
```
If you do still plan on doing a PR, please try to match the internal coding style more closely. Your code here is pretty close, but make sure that the pointer types look `like* this` instead of `like *this`.

Overall, I like your idea, but I think just sticking with `hashmap_iterate()` is probably still the best solution because it gives the user more freedom and isn't that difficult to use.

**Comment by ahmed-debbech** [comment]
I understand. 
I can't figure out what is the resulting keys ahead of time because that's the point the function i added should loop through the map to know, and for the key length you are right! , i didn't manage that.
I will consider making a callback function as well.
And to be honest i thiugh about using `hashmap_iterate` in my function but it dodn't seem to help because even the call back function provides no way to return an array of keys because the callback function is inernal in `hashmap_iterate` so no outout from the function itself that's why i rewrote it again.


I will try to improve my solution as you noted and you can decide to merge or not later.
Thank you for the review!

**Comment by Mashpoe** [comment]
Yeah, you definitely cannot know the number of matches ahead of time, I just worded that poorly. I was trying to say that the user would have to know the number of matches ahead of time in order for the function to be useful in its current state.

< And to be honest i thiugh about using hashmap_iterate in my function but it dodn't seem to help because even the call back function provides no way to return an array of keys because the callback function is inernal in hashmap_iterate so no outout from the function itself that's why i rewrote it again.

I also wasn't trying to say that you have to use `hashmap_iterate()` in the function you are trying to make, but that it could be used as an alternative to the function you wrote. Also, you _can_ get output from `hashmap_iterate()` by using the user pointer:

```c
struct iter_input
{
	// the value we are searching for
	uintptr_t search_value;
	int count;		// the size of the array
	int capacity;	// amount of space allocated in the array
	void **key_arr; // an array of keys
};

void iter_callback(void *key, size_t ksize, uintptr_t value, void *usr)
{
	struct iter_input *input = (struct iter_input *)usr;

	if (value != input->search_value)
		return;

	++input->count;

	if (input->count > input->capacity)
	{
		input->capacity *= 2;
		input->key_arr = realloc(input->key_arr, sizeof(void *) * input->capacity);
	}

	input->key_arr[input->count - 1] = key;
}

/*
...
*/

int main(int argc, const char* argv[])
{

	hashmap* m = hashmap_create();

	// matching keys
	hashmap_set(m, hashmap_str_lit("hello"), 400);
	hashmap_set(m, hashmap_str_lit("world"), 400);
	hashmap_set(m, hashmap_str_lit("foo"), 400);
	hashmap_set(m, hashmap_str_lit("bar"), 400);
	// non-matching keys
	hashmap_set(m, hashmap_str_lit("oof"), 600);
	hashmap_set(m, hashmap_str_lit("baz"), 500);

	// search for the value `400`, set count to initial value of `0`, allocate initial space of 1 array item
	struct iter_input input = {400, 0, 1, malloc(sizeof(void*))};
        
        // use the user pointer to get output from `hashmap_iterate()`
	hashmap_iterate(m, iter_callback, &input);

	// print out the resulting array items
	for (int i = 0; i < input.count; ++i)
	{
		printf("key %i: %s\n", i, input.key_arr[i]);
	}

	// free the array now that we're done with it:
	free(input.key_arr);
}
```
This should print the following result:

```
key 0: hello
key 1: world
key 2: foo
key 3: bar
```

Obviously this is a bit clunky, and if you wanted to add this to the library itself you you would have to define a new struct and give the user access to it. This also doesn't solve the key length problem. This is why I think it should be up to the user to implement their own version of this to suit their individual needs, since adding this feature would require adding a new type to `map.h` and it would take a decent amount of documentation to properly explain how to use it.

If you can think of a better solution I would be happy to look at it though :)

**Comment by ahmed-debbech** [comment]
I understand. 
You are right about how to use `hashmap_iterate` callbacks to fulfill the needs of the function that i want to add. I didn't know it is possible but you gave a great example though! also i though adding functions like mine would really make the library huge but it will make a good rich API that is so easy to use just by function calls.

**Pull request closed without merging**
